spring:   
 
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver  
    username: root  
    password: root  
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
     prefix: classpath:/templates/
     suffix: .html
     cache: false
     model: HTML5
     encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #设置json返回日期格式
    timeZone: GMT+8   				#设置时区,否则可能前台返回时间与数据库不一致
mybatis:  
    mapperLocations: classpath:mapper/*.xml  
    typeAliasesPackage: com.hmcmsdemo.model
    config-locations: classpath:mybatis-conf.xml